# Generated by Django 5.0 on 2023-12-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(verbose_name='Дата/Время')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('height', models.IntegerField(default=500, verbose_name='Высота экрана')),
                ('width', models.IntegerField(default=500, verbose_name='Ширина экрана')),
                ('scale', models.IntegerField(default=5, verbose_name='Размер шрифта')),
                ('thickness', models.IntegerField(default=3, verbose_name='Толщина шрифта')),
            ],
        ),
    ]
